apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zqqeunt4a-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zqqeunt4a-nodejs 
  name: zqqeunt4a-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: zqqeunt4a-nodejs 
